Move generator-script to its own .cabal file

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -120,16 +120,18 @@ install:
   - touch cabal.project
   - |
     echo "packages: ." >> cabal.project
+    echo "packages: ./generator-script" >> cabal.project
   - |
-    echo "package constraint-tuples"  >> cabal.project
-    echo "  flags: +generator-script" >> cabal.project
-    echo ""                           >> cabal.project
-    echo "package constraint-tuples"  >> cabal.project
-    echo "  ghc-options: -Werror"     >> cabal.project
-  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(constraint-tuples)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
+    echo "package constraint-tuples" >> cabal.project
+    echo "  ghc-options: -Werror"    >> cabal.project
+    echo ""                          >> cabal.project
+    echo "package generator-script"  >> cabal.project
+    echo "  ghc-options: -Werror"    >> cabal.project
+  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(constraint-tuples|generator-script)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
   - cat cabal.project.local || true
   - if [ -f "./configure.ac" ]; then (cd "." && autoreconf -i); fi
+  - if [ -f "./generator-script/configure.ac" ]; then (cd "./generator-script" && autoreconf -i); fi
   - ${CABAL} v2-freeze $WITHCOMPILER ${TEST} ${BENCH} | color_cabal_output
   - "cat cabal.project.freeze | sed -E 's/^(constraints: *| *)//' | sed 's/any.//'"
   - rm  cabal.project.freeze
@@ -144,18 +146,20 @@ script:
   - find . -maxdepth 1 -type f -name '*.tar.gz' -exec tar -xvf '{}' \;
   - find . -maxdepth 1 -type f -name '*.tar.gz' -exec rm       '{}' \;
   - PKGDIR_constraint_tuples="$(find . -maxdepth 1 -type d -regex '.*/constraint-tuples-[0-9.]*')"
+  - PKGDIR_generator_script="$(find . -maxdepth 1 -type d -regex '.*/generator-script-[0-9.]*')"
   # Generate cabal.project
   - rm -rf cabal.project cabal.project.local cabal.project.freeze
   - touch cabal.project
   - |
     echo "packages: ${PKGDIR_constraint_tuples}" >> cabal.project
+    echo "packages: ${PKGDIR_generator_script}" >> cabal.project
   - |
-    echo "package constraint-tuples"  >> cabal.project
-    echo "  flags: +generator-script" >> cabal.project
-    echo ""                           >> cabal.project
-    echo "package constraint-tuples"  >> cabal.project
-    echo "  ghc-options: -Werror"     >> cabal.project
-  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(constraint-tuples)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
+    echo "package constraint-tuples" >> cabal.project
+    echo "  ghc-options: -Werror"    >> cabal.project
+    echo ""                          >> cabal.project
+    echo "package generator-script"  >> cabal.project
+    echo "  ghc-options: -Werror"    >> cabal.project
+  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(constraint-tuples|generator-script)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
   - cat cabal.project.local || true
   # Building with tests and benchmarks...
@@ -163,6 +167,7 @@ script:
   - ${CABAL} v2-build $WITHCOMPILER ${TEST} ${BENCH} all | color_cabal_output
   # cabal check...
   - (cd ${PKGDIR_constraint_tuples} && ${CABAL} -vnormal check)
+  - (cd ${PKGDIR_generator_script} && ${CABAL} -vnormal check)
   # haddock...
   - ${CABAL} v2-haddock $WITHCOMPILER ${TEST} ${BENCH} all | color_cabal_output
 
